# Generated by Django 3.0.4 on 2020-03-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Signup',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('role', models.CharField(default='null', max_length=50)),
            ],
        ),
    ]
