# Generated by Django 3.0.4 on 2020-03-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0002_user_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_signup',
            name='password',
            field=models.TextField(),
        ),
    ]
