# Generated by Django 3.0.3 on 2020-03-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0003_auto_20200313_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_signup',
            name='token',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='user_signup',
            name='verify',
            field=models.CharField(default='unverified', max_length=100),
        ),
        migrations.AlterField(
            model_name='user_signup',
            name='password',
            field=models.TextField(default=''),
        ),
    ]
