# Generated by Django 3.0.4 on 2020-04-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Signup',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.TextField(default='')),
                ('role', models.CharField(default='null', max_length=50)),
            ],
        ),
    ]
