# Generated by Django 3.0.4 on 2020-04-02 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Signup',
            new_name='Signup',
        ),
    ]
