# Generated by Django 3.0.4 on 2020-04-02 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20200402_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(default='', max_length=255)),
                ('Last_Name', models.CharField(default='', max_length=255)),
                ('Gender', models.CharField(default='', max_length=255)),
                ('Address', models.CharField(default='', max_length=255)),
                ('Phone_Number', models.CharField(default='', max_length=25)),
                ('Dob', models.CharField(default='', max_length=20)),
                ('img', models.ImageField(default='dummy.jpg', upload_to='upload/')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Signup')),
            ],
        ),
    ]
