# Generated by Django 3.0.4 on 2020-04-02 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Did', models.AutoField(primary_key=True, serialize=False)),
                ('Department_name', models.CharField(default='', max_length=255)),
                ('Dep_Description', models.TextField(default='')),
                ('Instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Instructor')),
            ],
        ),
    ]
