# Generated by Django 3.0.4 on 2020-04-02 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Cid', models.AutoField(primary_key=True, serialize=False)),
                ('Course_name', models.CharField(default='', max_length=255)),
                ('Course_Description', models.TextField(default='')),
                ('Course_code', models.CharField(default='', max_length=20)),
                ('Issue_Date', models.DateTimeField(auto_now_add=True)),
                ('Total_Marks', models.IntegerField(default=0)),
                ('Obtain_Marks', models.IntegerField(default=0)),
                ('MidTerm_Marks', models.IntegerField(default=0)),
                ('Department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Department')),
                ('Instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Instructor')),
            ],
        ),
    ]
