# Generated by Django 3.0.4 on 2020-04-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='username',
        ),
    ]
