# Generated by Django 3.0.4 on 2020-04-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_remove_instructor_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
