# Generated by Django 3.0.4 on 2020-04-02 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0004_auto_20200313_1608'),
        ('faculty', '0007_delete_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lmsapp.User_Signup'),
        ),
    ]
