# Generated by Django 3.0.4 on 2020-04-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0009_remove_instructor_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Signup',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.TextField(default='')),
                ('role', models.CharField(default='null', max_length=50)),
                ('verify', models.CharField(default='unverified', max_length=100)),
            ],
        ),
    ]
