# Generated by Django 3.0.4 on 2020-04-02 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0010_user_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='username',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='faculty.User_Signup'),
        ),
    ]
