# Generated by Django 3.0.4 on 2020-04-02 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0011_instructor_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materialclass',
            fields=[
                ('Materailid', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(default='Title', max_length=100)),
                ('Category', models.CharField(choices=[('ebooks', 'E-BOOKS'), ('lectures', 'Online Lecture')], max_length=100)),
                ('MaterailFile', models.FileField(default='Notdata', upload_to='InstructorMaterials')),
                ('Course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Course')),
                ('Instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Instructor')),
            ],
        ),
    ]
