# Generated by Django 3.0.4 on 2020-04-03 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0011_instructor_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='materialcategory',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('Instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Instructor')),
            ],
        ),
    ]
