# Generated by Django 3.0.4 on 2020-04-03 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0012_materialclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigment',
            fields=[
                ('AsssigmentId', models.AutoField(primary_key=True, serialize=False)),
                ('AssigmentTitle', models.CharField(default='Title', max_length=100)),
                ('AssigmentDesc', models.TextField(default='Assigment Description', max_length=400)),
                ('AssigmentFile', models.FileField(default='#', upload_to='Assigments/')),
                ('Course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Course')),
                ('Instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Instructor')),
            ],
        ),
    ]
