# Generated by Django 3.0.4 on 2020-04-03 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0012_material_materialcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='faculty.materialcategory'),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(default='mypic', upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='materialcategory',
            name='cname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
