# Generated by Django 3.0.4 on 2020-04-03 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0013_auto_20200403_1219'),
        ('faculty', '0012_materialclass'),
    ]

    operations = [
    ]
