# Generated by Django 3.0.4 on 2020-04-03 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0013_assigment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assigment',
            new_name='AssigmentModel',
        ),
    ]
