# Generated by Django 3.0.4 on 2020-04-03 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0014_auto_20200403_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('NotificationId', models.AutoField(primary_key=True, serialize=False)),
                ('NotificationTitle', models.CharField(default='Notification Title', max_length=100)),
                ('NotificationDesc', models.TextField(default='Notification Description', max_length=200)),
                ('Course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Course')),
                ('Instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Instructor')),
            ],
        ),
    ]
