# Generated by Django 3.0.4 on 2020-04-03 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0014_merge_20200403_1550'),
    ]

    operations = [
        migrations.DeleteModel(
            name='material',
        ),
        migrations.DeleteModel(
            name='materialcategory',
        ),
    ]
