# Generated by Django 3.0.4 on 2020-04-03 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0015_notificationmodel'),
        ('faculty', '0015_auto_20200403_1715'),
    ]

    operations = [
    ]
