# Generated by Django 3.0.4 on 2020-04-06 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0017_notificationmodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='syllabus',
            fields=[
                ('syllabusId', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.CharField(default='', max_length=100)),
                ('outline', models.FileField(default='#', upload_to='Assigments/')),
                ('Course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Course')),
                ('Department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Department')),
                ('Instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Instructor')),
            ],
        ),
    ]
