# Generated by Django 3.0.4 on 2020-04-06 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0018_syllabus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='syllabus',
            new_name='Teacher_syllabus',
        ),
    ]
