# Generated by Django 3.0.4 on 2020-04-07 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0020_teacherapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherapplication',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 7, 12, 18, 39, 517776)),
        ),
    ]
