# Generated by Django 3.0.4 on 2020-04-07 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0021_auto_20200407_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherapplication',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 7, 14, 19, 9, 501603)),
        ),
    ]
