# Generated by Django 3.0.4 on 2020-04-07 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0024_auto_20200407_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherapplication',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 7, 15, 11, 6, 274731)),
        ),
    ]
