# Generated by Django 3.0.4 on 2020-04-07 11:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0029_auto_20200407_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherapplication',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 7, 16, 32, 55, 440239)),
        ),
        migrations.CreateModel(
            name='User_Stories',
            fields=[
                ('storyid', models.AutoField(primary_key=True, serialize=False)),
                ('I_want_to', models.CharField(default='', max_length=200)),
                ('So_that_I_can', models.CharField(default='', max_length=500)),
                ('Category', models.CharField(choices=[('new', 'NEW'), ('old', 'OLD')], max_length=100)),
                ('Department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Department')),
                ('Instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Instructor')),
            ],
        ),
    ]
