# Generated by Django 3.0.4 on 2020-04-09 20:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0041_auto_20200409_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 9, 13, 47, 34, 261216)),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 9, 13, 47, 34, 259246)),
        ),
        migrations.CreateModel(
            name='CourseVideos',
            fields=[
                ('VideoId', models.AutoField(primary_key=True, serialize=False)),
                ('VideoTitle', models.CharField(default='Video Title', max_length=100)),
                ('VideoDesc', models.TextField(default='Description', max_length=100)),
                ('CourseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Course')),
                ('InstructerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Instructor')),
            ],
        ),
    ]
