# Generated by Django 3.0.4 on 2020-04-09 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0042_auto_20200409_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideos',
            name='VideoFile',
            field=models.FileField(default='Video.mp4', upload_to='facultyvideo/'),
        ),
        migrations.AlterField(
            model_name='query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 9, 13, 55, 5, 35256)),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 9, 13, 55, 5, 33261)),
        ),
    ]
