# Generated by Django 3.0.4 on 2020-04-13 06:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0046_auto_20200410_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 13, 11, 23, 51, 143332)),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 13, 11, 23, 51, 141323)),
        ),
        migrations.CreateModel(
            name='Faculty_Development',
            fields=[
                ('Faculty_Development_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='Name', max_length=100)),
                ('Department', models.CharField(default='Department', max_length=100)),
                ('Highest_Degree', models.CharField(default='Degree', max_length=100)),
                ('Subject', models.CharField(default='Subject', max_length=100)),
                ('Course_you_Teach', models.CharField(default='Subject', max_length=100)),
                ('Core_Area_to_you_would_like_to_develop', models.CharField(default='Skills', max_length=100)),
                ('Teacher_Research_Ratio', models.TextField(default='research', max_length=450)),
                ('particular_area_of_work', models.CharField(default='Area', max_length=100)),
                ('area_of_expertise', models.TextField(default='expertise', max_length=450)),
                ('Instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Instructor')),
            ],
        ),
    ]
