# Generated by Django 3.0.4 on 2020-04-13 06:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0048_auto_20200413_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 13, 11, 44, 7, 267359)),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 13, 11, 44, 7, 267359)),
        ),
        migrations.CreateModel(
            name='Faculty_Evaluation',
            fields=[
                ('Faculty_Evaluation_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Report_Name', models.CharField(default='Name', max_length=200)),
                ('Report_File', models.FileField(default='Notdata', upload_to='report')),
                ('Course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Course')),
                ('Department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Department')),
                ('InstructerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Instructor')),
            ],
        ),
    ]
