# Generated by Django 3.0.4 on 2020-04-13 07:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0049_auto_20200413_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 13, 12, 14, 41, 638383)),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 13, 12, 14, 41, 637382)),
        ),
        migrations.CreateModel(
            name='Exam_Result',
            fields=[
                ('Exam_Result_id', models.AutoField(primary_key=True, serialize=False)),
                ('Project_Marks', models.IntegerField(default='')),
                ('Quiz_Assignment_Marks', models.IntegerField(default='')),
                ('Midterm_Marks', models.IntegerField(default='')),
                ('Final_Marks', models.IntegerField(default='')),
                ('Total_Marks', models.IntegerField(default='')),
                ('Course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Course')),
                ('Department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Department')),
                ('InstructerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Instructor')),
            ],
        ),
    ]
