# Generated by Django 3.0.4 on 2020-04-14 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0051_auto_20200414_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('SamesterId', models.AutoField(primary_key=True, serialize=False)),
                ('Samester_Name', models.CharField(default='1st Samester', max_length=50)),
                ('Samester_Code', models.CharField(default='CS001', max_length=20)),
                ('Samester_Year', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 14, 12, 7, 19, 676656)),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 14, 12, 7, 19, 674659)),
        ),
    ]
