# Generated by Django 3.0.4 on 2020-04-14 07:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0052_auto_20200414_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Semester_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='faculty.Semester'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 14, 12, 9, 35, 976681)),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 14, 12, 9, 35, 974762)),
        ),
    ]
