# Generated by Django 3.0.4 on 2020-04-14 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0053_auto_20200414_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Semester_id',
        ),
        migrations.AlterField(
            model_name='query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 14, 12, 14, 1, 866623)),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 14, 12, 14, 1, 861668)),
        ),
    ]
