# Generated by Django 3.0.4 on 2020-04-20 07:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0071_auto_20200420_1247'),
        ('faculty', '0082_auto_20200420_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_result',
            name='Student_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student.Student_Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 20, 12, 46, 57, 366296)),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 20, 12, 46, 57, 363753)),
        ),
    ]
