# Generated by Django 3.0.4 on 2020-05-06 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0089_auto_20200502_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_result',
            name='Status',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AlterField(
            model_name='query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 6, 23, 56, 52, 425568)),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 6, 23, 56, 52, 422568)),
        ),
    ]
