# Generated by Django 3.0.4 on 2020-05-07 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0090_auto_20200506_2356'),
        ('faculty', '0091_auto_20200507_0255'),
    ]

    operations = [
    ]
