# Generated by Django 3.0.4 on 2020-05-09 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0096_merge_20200509_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_result',
            name='GPA',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AlterField(
            model_name='query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 9, 18, 0, 28, 700568)),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 9, 18, 0, 28, 698568)),
        ),
    ]
