# Generated by Django 3.0.4 on 2020-03-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=255)),
                ('Occupation', models.CharField(default='', max_length=255)),
                ('Company_Name', models.CharField(default='', max_length=255)),
                ('Phone', models.CharField(default='', max_length=15)),
                ('Personal_info', models.TextField(default='')),
                ('Facebook', models.URLField(default='', max_length=500)),
                ('Twitter', models.URLField(default='', max_length=500)),
                ('Linkedin', models.URLField(default='', max_length=500)),
                ('Google_Plus', models.URLField(default='', max_length=500)),
                ('img', models.ImageField(default='dummy.jpg', upload_to='upload/')),
            ],
        ),
    ]
