# Generated by Django 3.0.4 on 2020-03-19 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('cid', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
                ('videocategory', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='id',
        ),
        migrations.AddField(
            model_name='teacher',
            name='tid',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='uname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='courseuploaddetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_title', models.CharField(default='', max_length=500)),
                ('Course_price', models.IntegerField(default=0)),
                ('Course_start', models.DateTimeField(auto_now_add=True)),
                ('Course_end', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(default='dummy.jpg', upload_to='upload/')),
                ('Course_info', models.TextField(default='')),
                ('coursename', models.CharField(default='', max_length=255)),
                ('videolink', models.URLField(default='', max_length=500)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.category')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.teacher')),
            ],
        ),
    ]
