# Generated by Django 3.0.4 on 2020-03-19 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0004_auto_20200313_1608'),
        ('instructor', '0002_auto_20200319_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='uname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsapp.User_Signup'),
        ),
    ]
