# Generated by Django 3.0.4 on 2020-03-19 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_auto_20200320_0121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='courseuploaddetails',
        ),
    ]
