# Generated by Django 3.0.4 on 2020-03-19 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_delete_courseuploaddetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
