# Generated by Django 3.0.4 on 2020-03-19 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0004_auto_20200313_1608'),
        ('instructor', '0005_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('catid', models.AutoField(primary_key=True, serialize=False)),
                ('cattitle', models.CharField(default='', max_length=255)),
                ('catdesct', models.CharField(default='', max_length=255)),
                ('catimage', models.ImageField(default='dummy.jpg', upload_to='upload/')),
            ],
        ),
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('levelid', models.AutoField(primary_key=True, serialize=False)),
                ('leveltitle', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('Course_title', models.CharField(default='', max_length=255)),
                ('Course_description', models.TextField(default=0)),
                ('Course_requirment', models.TextField(default=0)),
                ('Course_start_date', models.DateTimeField(blank=True)),
                ('Course_Price', models.ImageField(default=0, upload_to='')),
                ('Course_Duration', models.TextField(default=0)),
                ('Course_Thumbnail', models.ImageField(default='dummy.jpg', upload_to='upload/')),
                ('Course_Level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.CourseLevel')),
                ('Course_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.CourseCategory')),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsapp.User_Signup')),
            ],
        ),
    ]
