# Generated by Django 3.0.4 on 2020-03-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0006_course_coursecategory_courselevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_Price',
            field=models.TextField(default=0),
        ),
    ]
