# Generated by Django 3.0.4 on 2020-03-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0007_auto_20200320_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
