# Generated by Django 3.0.1 on 2020-03-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0008_auto_20200320_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='tid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
