# Generated by Django 3.0.4 on 2020-03-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categroypost',
            fields=[
                ('catPostId', models.AutoField(primary_key=True, serialize=False)),
                ('catTitle', models.CharField(default='Category title', max_length=100)),
            ],
        ),
    ]
