# Generated by Django 3.0.1 on 2020-03-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='eventtitle',
            field=models.CharField(default='', max_length=255),
        ),
    ]
