# Generated by Django 3.0.5 on 2020-05-06 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('msgid', models.AutoField(primary_key=True, serialize=False)),
                ('msgfrom', models.IntegerField()),
                ('msgto', models.IntegerField()),
                ('msg', models.TextField(max_length=3000)),
                ('sender_name', models.CharField(max_length=100)),
                ('is_read', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
