# Generated by Django 3.0.5 on 2020-05-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_auto_20200507_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='userrole',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
