# Generated by Django 3.0.5 on 2020-05-08 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_messages_userrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='userrole',
        ),
    ]
