# Generated by Django 3.0.4 on 2020-04-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Samesters',
            fields=[
                ('SamesterId', models.AutoField(primary_key=True, serialize=False)),
                ('Samester_Name', models.CharField(default='1st Samester', max_length=50)),
                ('Samester_Code', models.CharField(default='CS001', max_length=20)),
                ('Samester_Year', models.DateField()),
            ],
        ),
    ]
