# Generated by Django 3.0.4 on 2020-04-06 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0019_auto_20200406_1829'),
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendarModel',
            fields=[
                ('AcademicCalendarId', models.AutoField(primary_key=True, serialize=False)),
                ('AcademicCalendarTitle', models.CharField(default='Title', max_length=100)),
                ('AcademicCalendarDesc', models.TextField(default='Title', max_length=400)),
                ('AcademicCalendarStartDate', models.DateTimeField()),
                ('AcademicCalendarEndDate', models.DateTimeField()),
                ('AcademicCalendarLocation', models.CharField(default='Address', max_length=240)),
                ('Department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Department')),
            ],
        ),
    ]
