# Generated by Django 3.0.4 on 2020-04-06 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_academiccalendarmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academiccalendarmodel',
            name='Department_id',
        ),
    ]
