# Generated by Django 3.0.4 on 2020-04-07 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0022_auto_20200407_1419'),
        ('administrator', '0003_remove_academiccalendarmodel_department_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyCalendarModel',
            fields=[
                ('FacultyCalendarId', models.AutoField(primary_key=True, serialize=False)),
                ('FacultyCalendarTitle', models.CharField(default='Title', max_length=100)),
                ('FacultyCalendarDesc', models.TextField(default='Title', max_length=400)),
                ('FacultyCalendarStartDate', models.DateTimeField()),
                ('FacultyCalendarEndDate', models.DateTimeField()),
                ('FacultyCalendarLocation', models.CharField(default='Address', max_length=240)),
                ('Department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Department')),
            ],
        ),
    ]
