# Generated by Django 3.0.4 on 2020-04-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_facultycalendarmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultycalendarmodel',
            name='Department_id',
        ),
    ]
