# Generated by Django 3.0.4 on 2020-04-07 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0029_auto_20200407_1550'),
        ('administrator', '0005_remove_facultycalendarmodel_department_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultycalendarmodel',
            name='Department_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='faculty.Department'),
            preserve_default=False,
        ),
    ]
