# Generated by Django 3.0.4 on 2020-04-08 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0032_auto_20200408_1349'),
        ('administrator', '0007_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('RoomId', models.AutoField(primary_key=True, serialize=False)),
                ('RoomName', models.CharField(default='Room Name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('roleid', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('assistantteacher', 'Assistant Teacher'), ('teacher', 'Teacher'), ('professor', 'Professor'), ('assistantprofessor', 'Assistant Professor'), ('hod', 'HOD'), ('registrar', 'Registrar'), ('dean', 'Dean'), ('viceChancelor', 'ViceChancelor'), ('librarian', 'Librarian')], max_length=100)),
                ('active', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=100)),
                ('date', models.DateField()),
                ('Instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Admin_Notification',
            fields=[
                ('NotificationId', models.AutoField(primary_key=True, serialize=False)),
                ('NotificationTitle', models.CharField(default='Notification Title', max_length=100)),
                ('NotificationDesc', models.TextField(default='Notification Description', max_length=200)),
                ('Department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Department')),
                ('Instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Instructor')),
            ],
        ),
    ]
