# Generated by Django 3.0.4 on 2020-04-08 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_admin_notification_role_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('ReservationId', models.AutoField(primary_key=True, serialize=False)),
                ('ReservationParticipants', models.CharField(default='Participants', max_length=200)),
                ('ReservationComments', models.TextField(default='Comments', max_length=350)),
                ('ReservationStartDateTime', models.DateTimeField()),
                ('ReservationEndDateTime', models.DateTimeField()),
                ('RoomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Rooms')),
            ],
        ),
    ]
