# Generated by Django 3.0.4 on 2020-04-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_roomreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='RoomStatus',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked')], default='Available', max_length=300),
        ),
    ]
