# Generated by Django 3.0.4 on 2020-04-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_rooms_roomstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='RoomCode',
            field=models.CharField(default='Room Code', max_length=10),
        ),
    ]
