# Generated by Django 3.0.4 on 2020-04-09 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_delete_roomreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('ReservationId', models.AutoField(primary_key=True, serialize=False)),
                ('ReservationParticipants', models.CharField(default='Participants', max_length=200)),
                ('ReservationComments', models.TextField(default='Comments', max_length=350)),
                ('ReservationStartDate', models.DateField()),
                ('ReservationStartTime', models.TimeField()),
                ('ReservationEndTime', models.TimeField()),
                ('RoomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Rooms')),
            ],
        ),
    ]
