# Generated by Django 3.0.4 on 2020-04-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_roomreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('MenuId', models.AutoField(primary_key=True, serialize=False)),
                ('MenuTitle', models.CharField(default='Menu Title', max_length=100)),
                ('MenuType', models.CharField(choices=[('Tea', 'Hi Tea'), ('lunchmedium', 'Lunch Medium Course'), ('Lunchnormalcourse', 'Lunch Normal Course')], max_length=50)),
            ],
        ),
    ]
