# Generated by Django 3.0.4 on 2020-04-09 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_menuorders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuorders',
            name='MenuId',
        ),
    ]
