# Generated by Django 3.0.4 on 2020-04-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0016_remove_menuorders_menuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuorders',
            name='OrderComments',
            field=models.TextField(default='Comments', max_length=350),
        ),
        migrations.AddField(
            model_name='menuorders',
            name='OrderParticipants',
            field=models.CharField(default='Participants', max_length=200),
        ),
    ]
