# Generated by Django 3.0.4 on 2020-04-09 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0044_auto_20200409_1411'),
        ('administrator', '0017_auto_20200409_0543'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyAttendence',
            fields=[
                ('FacultyAttendenceId', models.AutoField(primary_key=True, serialize=False)),
                ('FacultyAttendenceYear', models.TextField(default='December', max_length=50)),
                ('FacultyAttendenceMonth', models.TextField(default='April', max_length=50)),
                ('FacultyAttendencePresent', models.IntegerField(default=0)),
                ('FacultyAttendenceAbsent', models.IntegerField(default=0)),
                ('FacultyAttendenceTotal', models.FloatField(default=0.0)),
                ('Instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Instructor')),
            ],
        ),
    ]
