# Generated by Django 3.0.4 on 2020-04-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_facultyattendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='Formtitle',
            field=models.CharField(default='', max_length=100),
        ),
    ]
