# Generated by Django 3.0.4 on 2020-04-14 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0020_faculty_evaluation_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Samesters',
        ),
    ]
