# Generated by Django 3.0.4 on 2020-04-17 05:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0061_auto_20200417_1025'),
        ('administrator', '0021_delete_samesters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester_Schedule',
            fields=[
                ('Semester_Schedule_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Year', models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 10, 25, 48, 339972))),
                ('Semester_Schedule_File', models.FileField(default='Notdata', upload_to='semester_schedule')),
                ('Department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Department')),
                ('Semester_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Semester')),
            ],
        ),
    ]
