# Generated by Django 3.0.4 on 2020-04-17 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0023_auto_20200417_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester_schedule',
            name='Year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 11, 29, 5, 42441)),
        ),
    ]
