# Generated by Django 3.0.4 on 2020-04-17 06:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0064_auto_20200417_1133'),
        ('administrator', '0024_auto_20200417_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester_schedule',
            name='Year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 11, 32, 59, 833708)),
        ),
        migrations.CreateModel(
            name='Exam_Schedule',
            fields=[
                ('Exam_Schedule_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Year', models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 11, 32, 59, 836869))),
                ('Exam_Schedule_File', models.FileField(default='Notdata', upload_to='semester_schedule')),
                ('Department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Department')),
                ('Semester_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Semester')),
            ],
        ),
    ]
