# Generated by Django 3.0.4 on 2020-04-17 06:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0053_auto_20200417_1137'),
        ('administrator', '0025_auto_20200417_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_schedule',
            name='Year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 11, 37, 52, 29215)),
        ),
        migrations.AlterField(
            model_name='semester_schedule',
            name='Year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 11, 37, 52, 29215)),
        ),
        migrations.CreateModel(
            name='StudentAttendence',
            fields=[
                ('StudentAttendenceId', models.AutoField(primary_key=True, serialize=False)),
                ('StudentAttendenceYear', models.TextField(default='December', max_length=50)),
                ('StudentAttendenceMonth', models.TextField(default='April', max_length=50)),
                ('StudentAttendencePresent', models.IntegerField(default=0)),
                ('StudentAttendenceAbsent', models.IntegerField(default=0)),
                ('StudentAttendenceTotal', models.FloatField(default=0.0)),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Profile')),
            ],
        ),
    ]
