# Generated by Django 3.0.4 on 2020-04-17 06:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0054_auto_20200417_1145'),
        ('faculty', '0066_auto_20200417_1145'),
        ('administrator', '0026_auto_20200417_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendence',
            name='Course_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student.Student_Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentattendence',
            name='Department_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='faculty.Department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam_schedule',
            name='Year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 11, 45, 19, 846794)),
        ),
        migrations.AlterField(
            model_name='semester_schedule',
            name='Year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 11, 45, 19, 846163)),
        ),
    ]
