# Generated by Django 3.0.4 on 2020-04-17 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0029_auto_20200417_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='onlinesurvey',
            fields=[
                ('onlinesurvey_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_1', models.CharField(default='question1', max_length=200)),
                ('question_2', models.CharField(default='question2', max_length=200)),
                ('question_3', models.CharField(default='question3', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='exam_schedule',
            name='Year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 12, 34, 49, 133962)),
        ),
        migrations.AlterField(
            model_name='semester_schedule',
            name='Year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 12, 34, 49, 133962)),
        ),
    ]
