# Generated by Django 3.0.4 on 2020-04-18 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0037_auto_20200417_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement_Portal',
            fields=[
                ('Placement_Portal_id', models.AutoField(primary_key=True, serialize=False)),
                ('Job_Title', models.CharField(default='IT', max_length=200)),
                ('Name_of_Organization', models.CharField(default='xyz', max_length=200)),
                ('Company_Profile', models.CharField(default='Local', max_length=200)),
                ('Employment_Type', models.CharField(default='xyz', max_length=200)),
                ('Job_description', models.FileField(default='Notdata', upload_to='job')),
            ],
        ),
        migrations.AlterField(
            model_name='exam_schedule',
            name='Year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 18, 13, 4, 56, 674115)),
        ),
        migrations.AlterField(
            model_name='semester_schedule',
            name='Year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 18, 13, 4, 56, 673112)),
        ),
    ]
