# Generated by Django 3.0.4 on 2020-04-18 10:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0079_auto_20200418_1504'),
        ('administrator', '0039_auto_20200418_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_schedule',
            name='Year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 18, 15, 4, 11, 796436)),
        ),
        migrations.AlterField(
            model_name='semester_schedule',
            name='Year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 18, 15, 4, 11, 795433)),
        ),
        migrations.AlterField(
            model_name='studentattendence',
            name='Course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Course'),
        ),
    ]
