# Generated by Django 3.0.4 on 2020-05-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0051_auto_20200506_2356'),
        ('administrator', '0052_auto_20200507_0255'),
    ]

    operations = [
    ]
