# Generated by Django 3.0.4 on 2020-05-08 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0053_merge_20200508_0116'),
        ('administrator', '0055_auto_20200508_2325'),
    ]

    operations = [
    ]
