# Generated by Django 3.0.4 on 2020-05-13 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0059_auto_20200510_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccalendarmodel',
            name='Image',
            field=models.FileField(default='Notdata', upload_to='job'),
        ),
        migrations.AlterField(
            model_name='exam_schedule',
            name='Year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 14, 0, 1, 17, 679596)),
        ),
        migrations.AlterField(
            model_name='semester_schedule',
            name='Year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 14, 0, 1, 17, 678594)),
        ),
    ]
