# Generated by Django 3.0.4 on 2020-05-13 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0060_auto_20200514_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultycalendarmodel',
            name='Image',
            field=models.FileField(default='Notdata', upload_to='job'),
        ),
        migrations.AlterField(
            model_name='exam_schedule',
            name='Year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 14, 2, 23, 10, 96587)),
        ),
        migrations.AlterField(
            model_name='semester_schedule',
            name='Year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 14, 2, 23, 10, 94580)),
        ),
    ]
