# Generated by Django 3.0.4 on 2020-04-03 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0016_merge_20200403_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Samester',
            fields=[
                ('SamesterId', models.AutoField(primary_key=True, serialize=False)),
                ('Samester_Name', models.CharField(default='1st Samester', max_length=50)),
                ('Samester_Code', models.CharField(default='CS001', max_length=20)),
                ('Samester_Year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_Signup',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.TextField(default='')),
                ('verify', models.CharField(default='unverified', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Profile',
            fields=[
                ('StudentId', models.AutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(default='First Name', max_length=100)),
                ('Last_name', models.CharField(default='Last Name', max_length=100)),
                ('ContactNo', models.CharField(default='Contact No', max_length=100)),
                ('Address', models.CharField(default='Addresss', max_length=150)),
                ('DOB', models.DateField()),
                ('Profile', models.ImageField(default='Thumb.jpg', upload_to='StudentProfile/')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Signup')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Courses',
            fields=[
                ('StudentCoursesId', models.AutoField(primary_key=True, serialize=False)),
                ('Samester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Samester')),
                ('Student_coursesIds', models.ManyToManyField(blank=True, null=True, to='faculty.Course')),
            ],
        ),
    ]
