# Generated by Django 3.0.4 on 2020-04-07 10:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0024_auto_20200407_1510'),
        ('student', '0009_auto_20200407_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 7, 15, 10, 25, 473665)),
        ),
        migrations.AlterField(
            model_name='application',
            name='Instructor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Instructor'),
        ),
    ]
