# Generated by Django 3.0.4 on 2020-04-08 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0032_auto_20200408_1349'),
        ('student', '0017_auto_20200407_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 8, 13, 49, 47, 367075)),
        ),
        migrations.AlterField(
            model_name='student_courses',
            name='Student_coursesId',
            field=models.ManyToManyField(to='faculty.Course'),
        ),
    ]
