# Generated by Django 3.0.4 on 2020-04-14 07:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0056_auto_20200414_1243'),
        ('student', '0043_auto_20200414_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 14, 12, 43, 21, 736731)),
        ),
        migrations.CreateModel(
            name='Student_Course',
            fields=[
                ('Student_Course_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Courses', models.ManyToManyField(to='faculty.Course')),
                ('Department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Department')),
                ('Semester_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Semester')),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Profile')),
            ],
        ),
    ]
