# Generated by Django 3.0.4 on 2020-04-16 12:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0057_auto_20200416_1739'),
        ('student', '0044_auto_20200414_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 16, 17, 39, 7, 74408)),
        ),
        migrations.CreateModel(
            name='Student_Query_Admin',
            fields=[
                ('queryid', models.AutoField(primary_key=True, serialize=False)),
                ('querytitle', models.CharField(default='Reason Title', max_length=50)),
                ('querymessage', models.TextField(default='Reason query', max_length=350)),
                ('querydate', models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 16, 17, 39, 7, 81404))),
                ('querystatus', models.CharField(default='Pendding', max_length=30)),
                ('Course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Course')),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Profile')),
            ],
        ),
    ]
