# Generated by Django 3.0.4 on 2020-04-17 06:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0050_auto_20200417_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 11, 29, 5, 26752)),
        ),
        migrations.AlterField(
            model_name='student_query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 11, 29, 5, 42441)),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('Student_Registration_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Student_Registration_Code', models.CharField(default='000000', max_length=50)),
                ('Student_Program', models.CharField(default='Program', max_length=50)),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Profile')),
            ],
        ),
    ]
