# Generated by Django 3.0.4 on 2020-04-17 06:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0068_auto_20200417_1158'),
        ('student', '0055_auto_20200417_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 11, 58, 53, 70679)),
        ),
        migrations.AlterField(
            model_name='student_query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 11, 58, 53, 86328)),
        ),
        migrations.CreateModel(
            name='ScrunityForm',
            fields=[
                ('Scrunity_Form_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Student_Name', models.CharField(default='Name', max_length=100)),
                ('Program', models.CharField(default='Program', max_length=100)),
                ('Registration_no', models.CharField(default='0000000', max_length=100)),
                ('Date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 11, 58, 53, 86328))),
                ('Scrunity_Rechecking', models.CharField(default='recheck', max_length=100)),
                ('Research_for_Evalution', models.CharField(default='evaluation', max_length=300)),
                ('Voucher_Number', models.CharField(default='number', max_length=100)),
                ('Course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Course')),
            ],
        ),
    ]
