# Generated by Django 3.0.4 on 2020-04-17 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0060_auto_20200417_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_survey',
            name='question_3_Answer',
            field=models.CharField(default='strongagree', max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 12, 47, 39, 91720)),
        ),
        migrations.AlterField(
            model_name='scrunityform',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 12, 47, 39, 107342)),
        ),
        migrations.AlterField(
            model_name='student_query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 12, 47, 39, 107342)),
        ),
        migrations.AlterField(
            model_name='student_survey',
            name='question_2_Answer',
            field=models.CharField(default='notagree', max_length=10),
        ),
    ]
