# Generated by Django 3.0.4 on 2020-04-18 09:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0065_auto_20200418_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 18, 14, 3, 10, 832584)),
        ),
        migrations.AlterField(
            model_name='scrunityform',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 18, 14, 3, 10, 842039)),
        ),
        migrations.AlterField(
            model_name='student_query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 18, 14, 3, 10, 842039)),
        ),
        migrations.CreateModel(
            name='Job_Apply',
            fields=[
                ('Job_Apply', models.AutoField(primary_key=True, serialize=False)),
                ('Student_Name', models.CharField(default='Name', max_length=100)),
                ('Program', models.CharField(default='Program', max_length=100)),
                ('Job_Experirnce', models.TextField(default='0', max_length=10)),
                ('Cv', models.FileField(default='Notdata', upload_to='cv')),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Profile')),
            ],
        ),
    ]
