# Generated by Django 3.0.4 on 2020-04-18 11:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0067_auto_20200418_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_apply',
            old_name='Job_Apply',
            new_name='Job_Apply_id',
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 18, 16, 58, 0, 474511)),
        ),
        migrations.AlterField(
            model_name='scrunityform',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 18, 16, 58, 0, 480646)),
        ),
        migrations.AlterField(
            model_name='student_query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 18, 16, 58, 0, 478998)),
        ),
        migrations.CreateModel(
            name='Student_Submit_Evaluation',
            fields=[
                ('Student_Submit_Evaluation_id', models.AutoField(primary_key=True, serialize=False)),
                ('Student_Name', models.CharField(default='Name', max_length=100)),
                ('Student_Program', models.CharField(default='Program', max_length=100)),
                ('Report_File', models.FileField(default='Notdata', upload_to='report')),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Profile')),
            ],
        ),
    ]
