# Generated by Django 3.0.4 on 2020-04-29 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0072_auto_20200430_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_signup',
            name='role',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 30, 0, 5, 4, 136437)),
        ),
        migrations.AlterField(
            model_name='scrunityform',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 30, 0, 5, 4, 144742)),
        ),
        migrations.AlterField(
            model_name='student_query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 30, 0, 5, 4, 141653)),
        ),
        migrations.AlterField(
            model_name='teacher_appointment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 30, 0, 5, 4, 155782)),
        ),
    ]
