# Generated by Django 3.0.4 on 2020-04-29 22:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0086_auto_20200430_0309'),
        ('student', '0073_auto_20200430_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 30, 3, 9, 55, 167440)),
        ),
        migrations.AlterField(
            model_name='scrunityform',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 30, 3, 9, 55, 181435)),
        ),
        migrations.AlterField(
            model_name='student_query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 30, 3, 9, 55, 172434)),
        ),
        migrations.AlterField(
            model_name='teacher_appointment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 30, 3, 9, 55, 187435)),
        ),
        migrations.CreateModel(
            name='Student_Assigment',
            fields=[
                ('Student_Assigment_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Assigment_File', models.FileField(default='Notdata', upload_to='studentassigment')),
                ('Date_Time', models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 30, 3, 9, 55, 188437))),
                ('Course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Course')),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student_Profile')),
            ],
        ),
    ]
