# Generated by Django 3.0.4 on 2020-04-30 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0074_auto_20200430_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_assigment',
            name='roll',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 1, 0, 2, 13, 666256)),
        ),
        migrations.AlterField(
            model_name='scrunityform',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 1, 0, 2, 13, 670255)),
        ),
        migrations.AlterField(
            model_name='student_assigment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 1, 0, 2, 13, 674255)),
        ),
        migrations.AlterField(
            model_name='student_query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 1, 0, 2, 13, 668255)),
        ),
        migrations.AlterField(
            model_name='teacher_appointment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 1, 0, 2, 13, 673325)),
        ),
    ]
