# Generated by Django 3.0.4 on 2020-04-30 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0075_auto_20200501_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_assigment',
            name='section',
            field=models.CharField(default='xyz', max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 1, 0, 15, 43, 216381)),
        ),
        migrations.AlterField(
            model_name='scrunityform',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 1, 0, 15, 43, 219380)),
        ),
        migrations.AlterField(
            model_name='student_assigment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 1, 0, 15, 43, 224956)),
        ),
        migrations.AlterField(
            model_name='student_query_admin',
            name='querydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 1, 0, 15, 43, 218380)),
        ),
        migrations.AlterField(
            model_name='teacher_appointment',
            name='Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 1, 0, 15, 43, 223978)),
        ),
    ]
