# Generated by Django 3.0.5 on 2020-05-07 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0079_auto_20200507_0255'),
        ('student', '0078_auto_20200506_2356'),
    ]

    operations = [
    ]
