# Generated by Django 3.0.4 on 2020-05-08 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0080_merge_20200508_0116'),
        ('student', '0082_auto_20200508_2325'),
    ]

    operations = [
    ]
