# Generated by Django 3.0.4 on 2020-05-08 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0080_merge_20200508_0125'),
        ('student', '0083_merge_20200509_0252'),
    ]

    operations = [
    ]
